name: Setup CI Machine
description: Install dependencies for building TON on CI machine

inputs:
  os:
    description: 'OS'
    required: true

runs:
  using: composite

  steps:
    - uses: actions/cache@v4
      id: dependencies-cache
      with:
        path: ${{ env.PREFIX }}
        # NOTE: Changes to prefix are tracked automatically by GitHub via the "cache version".
        key: dependencies-${{ inputs.os }}-${{ hashFiles('**/.github/actions/setup/action.yml') }}

    - name: Install dependencies
      shell: bash
      run: |
        if ! which clang++-16; then
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16
        fi

        sudo apt-get update
        sudo apt-get install ccache libjemalloc-dev liblz4-dev libmicrohttpd-dev libsecp256k1-dev libsodium-dev zlib1g-dev

    - name: Create lib64 -> lib symlink
      if: steps.dependencies-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p "$PREFIX/lib"
        ln -s lib "$PREFIX/lib64"

    - name: Download library sources and check their hashes
      if: steps.dependencies-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget https://github.com/openssl/openssl/archive/refs/tags/openssl-3.1.4.tar.gz
        wget https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18.tar.gz
        wget https://github.com/lz4/lz4/releases/download/v1.9.4/lz4-1.9.4.tar.gz
        wget https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz
        wget https://ftpmirror.gnu.org/libmicrohttpd/libmicrohttpd-1.0.1.tar.gz
        sha256sum -c src/.github/actions/setup/checksums.txt

    - name: Compile and install OpenSSL
      if: steps.dependencies-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        tar xf openssl-3.1.4.tar.gz
        cd openssl-openssl-3.1.4

        export CC=clang-16
        export CXX=clang++-16

        ./config --prefix="$PREFIX" --openssldir="$PREFIX"
        make -j$(nproc) build_libs
        make -j$(nproc) install_sw

    - name: Compile and install libsodium
      if: steps.dependencies-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        tar xf libsodium-1.0.18.tar.gz
        cd libsodium-1.0.18

        export CC=clang-16
        export CXX=clang++-16

        ./configure --prefix="$PREFIX" --with-pic --enable-static
        make -j$(nproc)
        make -j$(nproc) install

    - name: Compile and install lz4
      if: steps.dependencies-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        tar xf lz4-1.9.4.tar.gz
        cd lz4-1.9.4

        export CC=clang-16
        export CXX=clang++-16

        CFLAGS=-fPIC make -j$(nproc)
        make -j$(nproc) install

    - name: Compile and install zlib
      if: steps.dependencies-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        tar xf zlib-1.3.1.tar.gz 
        cd zlib-1.3.1

        export CC=clang-16
        export CXX=clang++-16

        ./configure --prefix="$PREFIX" --static
        make -j$(nproc)
        make -j$(nproc) install

    - name: Compile and install libmicrohttpd
      if: steps.dependencies-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        tar xf libmicrohttpd-1.0.1.tar.gz
        cd libmicrohttpd-1.0.1

        export CC=clang-16
        export CXX=clang++-16

        ./configure --prefix="$PREFIX" --enable-static --disable-shared --disable-https --with-pic
        make -j$(nproc)
        make -j$(nproc) install

    - name: Remove build directories and archives
      if: steps.dependencies-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        rm -r openssl-3.1.4.tar.gz openssl-openssl-3.1.4
        rm -r libsodium-1.0.18.tar.gz libsodium-1.0.18
        rm -r lz4-1.9.4.tar.gz lz4-1.9.4
        rm -r zlib-1.3.1.tar.gz zlib-1.3.1
        rm -r libmicrohttpd-1.0.1.tar.gz libmicrohttpd-1.0.1
