FROM ubuntu:22.04 AS builder
RUN apt-get update && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake clang openssl libssl-dev zlib1g-dev gperf wget git ninja-build libsodium-dev libmicrohttpd-dev liblz4-dev pkg-config autoconf automake libtool libjemalloc-dev lsb-release software-properties-common gnupg bc vim libclang-common-14-dev libunwind-dev

RUN apt install bc

RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh 14 all && \
    rm -rf /var/lib/apt/lists/*


ENV CC=/usr/bin/clang-14
ENV CXX=/usr/bin/clang++-14
ENV CCACHE_DISABLE=1

WORKDIR /
RUN mkdir ton
WORKDIR /ton

COPY ./ ./

RUN ./build_opt.sh

