
const classProperties = [
	'verbosity',
	'shard_',
	'id_',
	'block_data',
	'collated_data',
	'main_promise',
	'prev_blocks',
	'prev_states',
	'after_merge_',
	'after_split_',
	'before_split_',
	'want_split_',
	'want_merge_',
	'is_key_block_',
	'update_shard_cc_',
	'prev_key_block_exists_',
	'debug_checks_',
	'outq_cleanup_partial_',
	'prev_key_seqno_',
	'stage_',
	'shard_pfx_',
	'shard_pfx_len_',
	'created_by_',

	'prev_state_root_',
	'state_usage_tree_',

	'error_ctx_',

	'mc_state_',
	'mc_state_root_',
	'mc_blkid_',
	'mc_seqno_',

	'block_root_',
	'collated_roots_',
	'virt_roots_',
	'top_shard_descr_dict_',
	'extra_collated_data_',
	'have_extra_collated_data_',

	'recover_create_msg_',
	'mint_msg_',

	'config_',
	'old_shard_conf_',
	'new_shard_conf_',
	'wc_info_',
	'old_mparams_',
	'accept_msgs_',

	'min_shard_ref_mc_seqno_',
	'max_shard_lt_',

	'global_id_',
	'vert_seqno_',
	'ihr_enabled_',
	'create_stats_enabled_',
	'prev_key_block_seqno_',
	'prev_key_block_',
	'prev_key_block_lt_',
	'block_limits_',
	'block_limit_status_',
	'total_gas_used_',
	'total_special_gas_used_',

	'start_lt_',
	'end_lt_',
	'now_',

	'rand_seed_',
	'storage_prices_',
	'storage_phase_cfg_',
	'compute_phase_cfg_',
	'action_phase_cfg_',
	'masterchain_create_fee_',
	'basechain_create_fee_',

	'neighbors_',
	'aux_mc_states_',

	'processed_upto_updated_',
	'sibling_out_msg_queue_',
	'sibling_processed_upto_',

	'block_create_count_',
	'block_create_total_',

	'in_msg_dict_',
	'out_msg_dict_',
	'account_blocks_dict_',


	'transaction_fees_',
	'total_burned_',
	'fees_burned_',


	'proc_lt_',
	'claimed_proc_lt_',
	'min_enq_lt_',
	'proc_hash_',
	'claimed_proc_hash_',
	'min_enq_hash_',

	'msg_proc_lt_',
	'msg_proc_lt_mutex_',
	'msg_emitted_lt_',

	'removed_dispatch_queue_messages_',
	'new_dispatch_queue_messages_',
	'account_expected_defer_all_messages_',
	'old_out_msg_queue_size_',
	'out_msg_queue_size_known_',
	'have_out_msg_queue_size_in_state_',

	'msg_metadata_enabled_',
	'deferring_messages_enabled_',
	'store_out_msg_queue_size_',

	'processed_account_dispatch_queues_',
	'have_unprocessed_account_dispatch_queue_',

	'workchain',


	'value_flow_',
	'import_created_',
	'import_fees_',
	'result_state_update_',


	'ps_',
	'ns_mutex_',
	// 'ns_',
	'ns_.id_',
	'ns_.root_',
	'ns_.global_id_',
	'ns_.utime_',
	'ns_.lt_',
	'ns_.mc_blk_seqno_',
	'ns_.min_ref_mc_seqno_',
	'ns_.vert_seqno_',
	'ns_.mc_blk_ref_',
	'ns_.mc_blk_lt_',
	'ns_.before_split_',
	'ns_.account_dict_',
	'ns_.shard_libraries_',
	'ns_.mc_state_extra_',
	'ns_.overload_history_',
	'ns_.underload_history_',
	'ns_.total_balance_',
	'ns_.total_validator_fees_',
	'ns_.global_balance_',
	'ns_.out_msg_queue_',
	'ns_.ihr_pending_',
	'ns_.block_create_stats_',
	'ns_.processed_upto_',
	'ns_.dispatch_queue_',
	'ns_.out_msg_queue_size_',
];

export default classProperties;
