/*
 * Copyright (c) 2026, TON CORE TECHNOLOGIES CO. L.L.C
 *
 * SPDX-License-Identifier: LGPL-2.0-or-later
 */

#include "td/utils/StringBuilder.h"
#include "td/utils/filesystem.h"
#include "td/utils/logging.h"
#include "td/utils/misc.h"
#include "td/utils/tests-snapshot.h"
#include "td/utils/tests.h"

namespace td {

namespace {

constexpr Slice delim_sep = Slice(" :: ");

bool is_comment_or_blank(Slice line) {
  return line.empty() || line[0] == '#';
}

}  // namespace

SnapshotStorage::SnapshotStorage(std::string path, bool update_mode)
    : path_(std::move(path)), update_mode_(update_mode) {
}

Status SnapshotStorage::load() {
  entries_.clear();
  auto data_result = read_file(path_);
  if (data_result.is_error()) {
    return Status::OK();
  }
  auto buffer = data_result.move_as_ok();
  Slice rest = buffer.as_slice();

  while (!rest.empty()) {
    // Read one line.
    auto nl = rest.find('\n');
    Slice line;
    if (nl == Slice::npos) {
      line = rest;
      rest = Slice();
    } else {
      line = Slice(rest.data(), nl);
      rest = Slice(rest.data() + nl + 1, rest.size() - nl - 1);
    }
    if (is_comment_or_blank(line)) {
      continue;
    }
    // Header: `<test_name> :: <key> :: <byte_len>`. Split on " :: " from the
    // right so the test name can contain " :: " if it ever needs to.
    auto last_sep = line.str().rfind(delim_sep.str());
    if (last_sep == std::string::npos) {
      return Status::Error(PSLICE() << "Bad snapshot file " << path_
                                    << ": expected `<name> :: <key> :: <len>` header, got: " << line);
    }
    Slice prefix = Slice(line.data(), last_sep);
    Slice len_str = Slice(line.data() + last_sep + delim_sep.size(), line.size() - last_sep - delim_sep.size());
    auto mid_sep = prefix.str().rfind(delim_sep.str());
    if (mid_sep == std::string::npos) {
      return Status::Error(PSLICE() << "Bad snapshot file " << path_ << ": missing key in header: " << line);
    }
    auto byte_len_r = td::to_integer_safe<size_t>(len_str);
    if (byte_len_r.is_error()) {
      return Status::Error(PSLICE() << "Bad snapshot file " << path_
                                    << ": header byte-length not an integer: " << line);
    }
    size_t byte_len = byte_len_r.move_as_ok();
    if (byte_len > rest.size()) {
      return Status::Error(PSLICE() << "Bad snapshot file " << path_ << ": entry claims " << byte_len
                                    << " bytes but only " << rest.size() << " remain after header: " << line);
    }
    std::string name(prefix.data(), mid_sep);
    std::string key(prefix.data() + mid_sep + delim_sep.size(), prefix.size() - mid_sep - delim_sep.size());
    std::string content(rest.data(), byte_len);
    rest = Slice(rest.data() + byte_len, rest.size() - byte_len);
    // Skip exactly one trailing '\n' that we emit as a cosmetic separator
    // after content; absent (e.g. if content already ends with '\n') is fine.
    if (!rest.empty() && rest[0] == '\n') {
      rest = Slice(rest.data() + 1, rest.size() - 1);
    }
    entries_[Key{std::move(name), std::move(key)}] = std::move(content);
  }
  return Status::OK();
}

Status SnapshotStorage::save() {
  CHECK(update_mode_);

  for (auto it = entries_.begin(); it != entries_.end();) {
    if (used_.count(it->first) == 0) {
      it = entries_.erase(it);
    } else {
      ++it;
    }
  }

  std::string out;
  out.append("# Auto-generated by EXPECT_SNAPSHOT.\n");
  out.append("# Run the test binary with TON_UPDATE_SNAPSHOTS=1 to regenerate.\n");
  for (const auto& [k, content] : entries_) {
    out.push_back('\n');
    out.append(k.test_name);
    out.append(delim_sep.data(), delim_sep.size());
    out.append(k.key);
    out.append(delim_sep.data(), delim_sep.size());
    out.append(PSTRING() << content.size());
    out.push_back('\n');
    out.append(content);
    out.push_back('\n');
  }

  return atomic_write_file(path_, out);
}

std::optional<std::string> SnapshotStorage::get(Slice test_name, Slice key) const {
  std::lock_guard guard{mutex_};
  auto it = entries_.find(Key{test_name.str(), key.str()});
  if (it == entries_.end()) {
    return std::nullopt;
  }
  return it->second;
}

void SnapshotStorage::set(std::string test_name, std::string key, std::string content) {
  std::lock_guard guard{mutex_};
  entries_[Key{std::move(test_name), std::move(key)}] = std::move(content);
}

void SnapshotStorage::mark_used(Slice test_name, Slice key) {
  std::lock_guard guard{mutex_};
  used_.insert(Key{test_name.str(), key.str()});
}

namespace detail {

namespace {

void log_snapshot_diff(Slice path, Slice test_name, Slice key, Slice expected, Slice actual) {
  td::StringBuilder sb;
  sb << "snapshot mismatch:\n";
  sb << "  file: " << path << "\n";
  sb << "  test: " << test_name << " :: " << key << "\n";
  sb << "  --- expected\n";
  Slice e = expected;
  while (!e.empty()) {
    auto nl = e.find('\n');
    Slice line = nl == Slice::npos ? e : Slice(e.data(), nl);
    sb << "  - " << line << "\n";
    if (nl == Slice::npos) {
      break;
    }
    e = Slice(e.data() + nl + 1, e.size() - nl - 1);
  }
  sb << "  +++ actual\n";
  Slice a = actual;
  while (!a.empty()) {
    auto nl = a.find('\n');
    Slice line = nl == Slice::npos ? a : Slice(a.data(), nl);
    sb << "  + " << line << "\n";
    if (nl == Slice::npos) {
      break;
    }
    a = Slice(a.data() + nl + 1, a.size() - nl - 1);
  }
  sb << "  hint: rerun with TON_UPDATE_SNAPSHOTS=1 if this change is intentional";
  LOG(ERROR) << sb.as_cslice();
}

}  // namespace

bool check_snapshot(Slice key, Slice actual) {
  auto* ctx = TestContext::get();
  Slice test_name = ctx->name();
  auto* storage = ctx->snapshots();
  if (storage == nullptr) {
    LOG(ERROR) << "EXPECT_SNAPSHOT for " << test_name << " :: " << key
               << " has no snapshot file configured (set TON_SNAPSHOT_FILE)";
    return false;
  }
  storage->mark_used(test_name, key);

  auto recorded = storage->get(test_name, key);
  if (recorded.has_value()) {
    if (Slice(*recorded) == actual) {
      return true;
    }
    if (storage->update_mode()) {
      storage->set(test_name.str(), key.str(), actual.str());
      LOG(INFO) << "snapshot updated: " << test_name << " :: " << key;
      return true;
    }
    log_snapshot_diff(storage->path(), test_name, key, *recorded, actual);
    return false;
  }

  if (storage->update_mode()) {
    storage->set(test_name.str(), key.str(), actual.str());
    LOG(INFO) << "snapshot recorded: " << test_name << " :: " << key;
    return true;
  }
  LOG(ERROR) << "no snapshot recorded for " << test_name << " :: " << key << " (file: " << storage->path()
             << "); rerun with TON_UPDATE_SNAPSHOTS=1";
  return false;
}

}  // namespace detail

}  // namespace td
